Repository pysal/pysal, pull requests merged in 2024-07, with the labels that each got.

#1310 add action for building docs
  .github/workflows/build_docs.yml
Labels: Docs

#1311 Fix doc build
  ci/312-latest.yaml
  docs/conf.py
  tools/package_releases.py
  tools/release.py
  tools/release.yaml
Labels: Docs

#1312 24.07rc1
  .pre-commit-config.yaml
  pyproject.toml
  tools/110-gitcount-tables.ipynb
  tools/release.yaml
  tools/release_info.py
Labels: release

#1326 prune tools dir - #1320
  tools/history.ipynb
  tools/package_releases.py
  tools/release.py
Labels: Infrastructure

#1325 Update build instructions in tools
  tools/110-gitcount-tables.ipynb
  tools/README.md
Labels: Infrastructure

#1328 update README format badge
  README.md
Labels: Maintenance

#1329 explicit intel chip test for macOS
  .github/workflows/testing.yml
Labels: CI

#1336 PR template & contrib updates
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Docs

#1332 Fix README.md package links
  README.md
Labels: Docs

#1342 Update release tooling for 24.01rc2
  tools/100-gitcount.ipynb
  tools/110-gitcount-tables.ipynb
  tools/frozen.ipynb
  tools/release.yaml
Labels: release

#1344 Move build tooling into scripts and remove notebooks
  pyproject.toml
  pysal/frozen.py
  tools/100-gitcount.ipynb
  tools/110-gitcount-tables.ipynb
  tools/Makefile
  tools/README.md
  tools/change_log.py
  tools/frozen.ipynb
  tools/frozen.py
  tools/gitcount.py
Labels: Infrastructure

#1345 DOC: move to pydata theme
  docs/_static/auto/references.el
  docs/_static/images/pysal_logo.png
  docs/_static/images/pysal_logo_light.png
  docs/_static/references.bib
  docs/api.rst
  docs/conf.py
  docs/index.rst
  docs/installation.rst
  pyproject.toml
Labels: Docs

#1331 Updating api and installation instructions
  README.md
  docs/installation.rst
Labels: Docs, release

#1346 REL: 24.07rc3
  pyproject.toml
  tools/release.yaml
Labels: release

#1349 Replace theme
  ci/312-latest.yaml
Labels: Docs

#1351 Update bib and turn off empty sidebars
  docs/_static/references.bib
  docs/conf.py
  docs/index.rst
  docs/installation.rst
Labels: Docs

#1352 Add workflow for rc prereleases
  .github/workflows/prerelease.yml
Labels: CI

#1353 CI: Update build and release instructions
  tools/README.md
Labels: CI

#1355 MNT: New release and publish action
  .github/workflows/release_and_publish.yml
  pyproject.toml
  tools/release.yaml
Labels: Maintenance
